//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Name { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string Village { get; set; }
        public string Mobile_No { get; set; }
        public int No_Of_Live_Stock { get; set; }
    }
}
